#!/usr/bin/env python3
import random


x = random.randint(0,10)

numbers = [0,1,2,3,4,5,6,7,8,9]
def get_num(list,x):
    low = 0
    hight = len(numbers)-1
    while low <= hight:
        mid = low + hight 
        guess = list[mid]
        if guess == x:
            return f"You got it and the number is {x}"
        if guess > x:
            hight -= 1 
        else:
            low += 1  
    return "rah wallo a satt "

print(get_num(numbers,x))
